### ISSUE TITLE
Add a launchpad icon

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/CompositionEditor#2]
Add a launchpad icon that will appear in Launcher. We have discussed that this should be a convention for all apps to have a launchpad icon + some minor information page that is displayed when the icon is clicked.

I have written some explanation here: https://starcounter.gitbooks.io/guidelines/content/app-icon.html

**Comment by Mackiovello** [comment]
To finish #22, I'll take this one, should follow the advice given in https://github.com/Starcounter/CompositionEditor/pull/22#issuecomment-310611111

**Comment by Mackiovello** [comment]
Handing over to you @Mihaiii

**Comment by warpech** [comment]
It would be good if the delivery of this continues in PR https://github.com/StarcounterApps/CompositionEditor/pull/22

**Comment by Mackiovello** [comment]
This is fixed with #28
