### ISSUE TITLE
Editor expands outside of screen

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterApps/CompositionEditor#23]
![editorexpand](https://user-images.githubusercontent.com/19392292/27287119-fa9b8bc0-5502-11e7-9360-a59b9bdc7629.gif)

**Comment by tomalec** [comment]
Are you sure it's a bug?
It was helpful to me few times, as I was preparing layout for narrow screen, which was hard to edit in so narrow editor.

**Comment by Mackiovello** [comment]
Well, the editor can still be expanded without the visual editor being pushed outside of the screen. If this is intentional, I'll close this issue.
