### ISSUE TITLE
Make ctrl + s save the composition

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterApps/CompositionEditor#26]
It would be convenient if ctrl + s would save the composition, then you can use the normal key combinations to save and close.

**Comment by mmnosek** [comment]
I like the idea of the shortcut, but I would be rather careful about overriding both:
- native browser & os system shortcuts (e.g. CTRL+S)
- native browser page content shortcuts (e.g. CTRL+F)

As it changes the expected behavior of the browser.

**Comment by Mackiovello** [comment]
Okay, let's skip it then
