### ISSUE TITLE
DescriptionPage.html is flawed

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/CompositionEditor#29]
Page https://github.com/StarcounterApps/CompositionEditor/blob/a47ac46a5337df6b840ec5bc16268c9a14c4c257/src/CompositionEditor/wwwroot/CompositionEditor/DescriptionPage.html is flawed for few reasons:

- I disagree with centering the text. The text coming from an app should look "defaultish", so it becomes better blendable. See: https://github.com/Starcounter/Home/issues/107
- Even, if we center the text, that should be done in `declarative-shadow-dom`.
- It is incorrect to have two `<h4>` elements just like that. Why `h4`, not `h1` and `p`? H-elements are for headings
- `<center>` tag is not part of HTML5: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center
- `template is="dom-bind"` is not needed on this page because there are no variables you are binding to

@tomalec anything to add?

cc @Mackiovello, @Mihaiii

**Comment by Mackiovello** [comment]
> I disagree with centering the text

That was my suggestion, after looking at the other apps I realize that we don't center the text anywhere else. I agree that it was a bad call.

I agree with the other points too. Should have checked more thoroughly.

**Comment by tomalec** [comment]
Just small note, that as we don't need `dom-bind` we also don't need Polymer. And personally, I'd wrap `<code>CTRL + E</code>`

**Comment by Mackiovello** [comment]
This one is fixed with #30. Would it be possible to make a release now @tomalec?

**Comment by tomalec** [comment]
Sure, do you want to make it? or should I do that?

**Comment by Mackiovello** [comment]
I can take care of it

Closing this issue as fixed
